import { ReactNode } from 'react';

import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';

import { Bootstrap } from '@/app/Bootstrap';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Bootstrap>{children}</Bootstrap>
    </body>
    </html>
  );
}
